const KEY='america250TrackerV1';
const initial={goals:{calories:1800,protein:140,fiber:30,water:90},foods:[],water:[],weights:[{date:new Date().toISOString().slice(0,10),value:230}],shopping:[],supplements:[]};
let state=load();let deferredPrompt=null;let stream=null;let scanning=false;let scannedProduct=null;
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
const $=id=>document.getElementById(id); const today=()=>new Date().toISOString().slice(0,10); $('foodDate').value=today();

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-open-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.openTab));
function showTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'smooth'})}

$('foodForm').onsubmit=e=>{e.preventDefault();state.foods.push({id:crypto.randomUUID(),date:$('foodDate').value,meal:$('meal').value,name:$('foodName').value.trim(),servings:+$('servings').value,calories:+$('calories').value,protein:+$('protein').value||0,carbs:+$('carbs').value||0,fat:+$('fat').value||0,fiber:+$('fiber').value||0,notes:$('foodNotes').value.trim(),barcode:''});e.target.reset();$('foodDate').value=today();$('servings').value=1;save()}
$('waterForm').onsubmit=e=>{e.preventDefault();state.water.push({id:crypto.randomUUID(),date:today(),ounces:+$('waterAmount').value});save()}
$('weightForm').onsubmit=e=>{e.preventDefault();state.weights.push({id:crypto.randomUUID(),date:today(),value:+$('weightAmount').value});save()}
$('shoppingForm').onsubmit=e=>{e.preventDefault();state.shopping.push({id:crypto.randomUUID(),item:$('shopItem').value.trim(),qty:$('shopQty').value,estimate:+$('shopEstimate').value||0,actual:+$('shopActual').value||0,store:$('shopStore').value,done:false});e.target.reset();$('shopQty').value=1;save()}
$('supplementForm').onsubmit=e=>{e.preventDefault();state.supplements.push({id:crypto.randomUUID(),name:$('suppName').value.trim(),dose:$('suppDose').value,timing:$('suppTiming').value,cost:+$('suppCost').value||0,approved:$('suppApproved').value,notes:$('suppNotes').value});e.target.reset();save()}
$('settingsForm').onsubmit=e=>{e.preventDefault();state.goals={calories:+$('goalCalories').value,protein:+$('goalProtein').value,fiber:+$('goalFiber').value,water:+$('goalWater').value};save()}
$('clearToday').onclick=()=>{if(confirm('Clear all food and water entries for today?')){state.foods=state.foods.filter(x=>x.date!==today());state.water=state.water.filter(x=>x.date!==today());save()}}
function del(type,id){state[type]=state[type].filter(x=>x.id!==id);save()}

function totalsFor(date){const foods=state.foods.filter(x=>x.date===date);const sum=k=>foods.reduce((a,x)=>a+(+x[k]||0)*(+x.servings||1),0);return {calories:sum('calories'),protein:sum('protein'),carbs:sum('carbs'),fat:sum('fat'),fiber:sum('fiber'),water:state.water.filter(x=>x.date===date).reduce((a,x)=>a+x.ounces,0)}}
function renderAll(){const t=totalsFor(today()),g=state.goals;$('caloriesUsed').textContent=Math.round(t.calories);$('calorieGoalText').textContent=g.calories;$('calorieRemaining').textContent=Math.max(0,Math.round(g.calories-t.calories));const pct=Math.min(100,(t.calories/g.calories)*100||0);$('calorieRing').style.background=`conic-gradient(var(--red) ${pct}%,#e5eaf2 ${pct}%)`;$('proteinUsed').textContent=`${Math.round(t.protein)} g`;$('fiberUsed').textContent=`${Math.round(t.fiber)} g`;$('waterUsed').textContent=`${Math.round(t.water)} oz`;$('proteinGoalText').textContent=g.protein;$('fiberGoalText').textContent=g.fiber;$('waterGoalText').textContent=g.water;const lw=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date)).at(-1);$('latestWeight').textContent=lw?`${lw.value} lb`:'—';$('weightAmount').value=lw?.value||230;['Calories','Protein','Fiber','Water'].forEach(k=>{$('goal'+k).value=g[k.toLowerCase()]});renderToday();renderHistory();renderShopping();renderSupplements()}
function renderToday(){const box=$('todayList'),rows=state.foods.filter(x=>x.date===today());box.innerHTML='';if(!rows.length){box.textContent='No food logged yet.';return}rows.forEach(x=>{const el=row(`${x.meal}: ${x.name}`,`${x.servings} serving(s) • ${Math.round(x.calories*x.servings)} cal • ${Math.round(x.protein*x.servings)}g protein`,()=>del('foods',x.id));box.append(el)})}
function row(title,sub,onDelete){const el=$('rowTemplate').content.firstElementChild.cloneNode(true);el.querySelector('.row-main').innerHTML=`<strong>${esc(title)}</strong><small>${esc(sub)}</small>`;el.querySelector('button').onclick=onDelete;return el}
function renderHistory(){const box=$('historyList');box.innerHTML='';const dates=[...new Set([...state.foods.map(x=>x.date),...state.water.map(x=>x.date)])].sort().reverse();if(!dates.length){box.textContent='No history yet.';return}dates.forEach(d=>{const t=totalsFor(d);box.append(row(d,`${Math.round(t.calories)} cal • ${Math.round(t.protein)}g protein • ${Math.round(t.fiber)}g fiber • ${Math.round(t.water)} oz water`,()=>{}));box.lastElementChild.querySelector('button').remove()})}
function renderShopping(){const box=$('shoppingList');box.innerHTML='';let est=0,act=0;state.shopping.forEach(x=>{est+=x.estimate;act+=x.actual;const el=row(`${x.done?'✓ ':''}${x.item}`,`${x.qty} • ${x.store} • est $${x.estimate.toFixed(2)} • actual $${x.actual.toFixed(2)}`,()=>del('shopping',x.id));el.querySelector('.row-main').onclick=()=>{x.done=!x.done;save()};box.append(el)});if(!state.shopping.length)box.textContent='Your shopping list is empty.';$('estimatedTotal').textContent=`$${est.toFixed(2)}`;$('actualTotal').textContent=`$${act.toFixed(2)}`}
function renderSupplements(){const box=$('supplementList');box.innerHTML='';state.supplements.forEach(x=>box.append(row(x.name,`${x.dose||'Dose not set'} • ${x.timing||'Timing not set'} • $${x.cost.toFixed(2)}/mo • ${x.approved}`,()=>del('supplements',x.id))));if(!state.supplements.length)box.textContent='No supplements added.'}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

$('barcodeForm').onsubmit=e=>{e.preventDefault();lookupBarcode($('barcodeInput').value.trim())};
async function lookupBarcode(code){if(!code)return;$('scanStatus').textContent='Looking up product…';$('productCard').hidden=true;try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json`);if(!r.ok)throw new Error('Lookup failed');const j=await r.json();if(j.status!==1||!j.product)throw new Error('Product not found');const p=j.product,n=p.nutriments||{};scannedProduct={barcode:code,name:p.product_name||p.generic_name||'Unnamed product',brand:p.brands||'',serving:p.serving_size||'1 serving',calories:num(n['energy-kcal_serving']??n['energy-kcal_100g']),protein:num(n.proteins_serving??n.proteins_100g),carbs:num(n.carbohydrates_serving??n.carbohydrates_100g),fat:num(n.fat_serving??n.fat_100g),fiber:num(n.fiber_serving??n.fiber_100g)};showProduct(scannedProduct);$('scanStatus').textContent='Product found. Verify values against the package label.'}catch(err){$('scanStatus').textContent=`${err.message}. Enter the nutrition manually on the Today tab.`}}
function num(v){return Number.isFinite(+v)?+v:0}
function showProduct(p){$('productCard').hidden=false;$('productTitle').textContent=p.name;$('productBrand').textContent=`${p.brand}${p.serving?' • '+p.serving:''}`;$('nutritionGrid').innerHTML=[['Calories',p.calories],['Protein',p.protein+' g'],['Carbs',p.carbs+' g'],['Fat',p.fat+' g'],['Fiber',p.fiber+' g'],['Barcode',p.barcode]].map(([a,b])=>`<div><small>${a}</small><strong>${b}</strong></div>`).join('')}
$('addScannedFood').onclick=()=>{if(!scannedProduct)return;state.foods.push({id:crypto.randomUUID(),date:today(),meal:$('scanMeal').value,name:scannedProduct.name,servings:+$('scanServings').value||1,calories:scannedProduct.calories,protein:scannedProduct.protein,carbs:scannedProduct.carbs,fat:scannedProduct.fat,fiber:scannedProduct.fiber,notes:`${scannedProduct.brand} • ${scannedProduct.serving}`,barcode:scannedProduct.barcode});save();showTab('today')}

$('startScan').onclick=async()=>{if(!('BarcodeDetector'in window)){alert('Camera barcode detection is not supported in this browser. Use the manual UPC box instead.');return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('camera').srcObject=stream;await $('camera').play();$('camera').style.display='block';$('startScan').disabled=true;$('stopScan').disabled=false;scanning=true;scanLoop()}catch(e){$('scanStatus').textContent='Camera permission was denied or unavailable.'}}
$('stopScan').onclick=stopCamera;function stopCamera(){scanning=false;stream?.getTracks().forEach(t=>t.stop());$('camera').style.display='none';$('startScan').disabled=false;$('stopScan').disabled=true}
async function scanLoop(){const detector=new BarcodeDetector({formats:['upc_a','upc_e','ean_8','ean_13']});while(scanning){try{const codes=await detector.detect($('camera'));if(codes.length){stopCamera();$('barcodeInput').value=codes[0].rawValue;lookupBarcode(codes[0].rawValue);break}}catch{}await new Promise(r=>setTimeout(r,300))}}

function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('exportJson').onclick=()=>download(`america250-backup-${today()}.json`,JSON.stringify(state,null,2),'application/json');
$('importJson').onchange=async e=>{try{state=JSON.parse(await e.target.files[0].text());save();alert('Backup restored.')}catch{alert('Invalid backup file.')}}
$('exportFoodCsv').onclick=()=>{const h=['Date','Meal','Food','Servings','Calories','Protein','Carbs','Fat','Fiber','Barcode','Notes'];const rows=state.foods.map(x=>h.map(k=>{const m={Date:x.date,Meal:x.meal,Food:x.name,Servings:x.servings,Calories:x.calories,Protein:x.protein,Carbs:x.carbs,Fat:x.fat,Fiber:x.fiber,Barcode:x.barcode,Notes:x.notes}[k]??'';return `"${String(m).replaceAll('"','""')}"`}).join(','));download(`food-log-${today()}.csv`,[h.join(','),...rows].join('\n'),'text/csv')}
$('resetApp').onclick=()=>{if(confirm('Erase all food, weight, shopping and supplement data?')){state=structuredClone(initial);save()}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{await deferredPrompt?.prompt();deferredPrompt=null;$('installBtn').hidden=true};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');renderAll();
